import { sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { products } from "./catalog";
import {
  complaintReasonEnum,
  orderStatusEnum,
  paymentMethodEnum,
} from "./enums";
import { users } from "./users";

/**
 * Orders.
 *
 * Critical guarantees enforced here:
 *
 * 1. **Idempotency** — `idempotency_key` is unique. The checkout endpoint accepts
 *    the same key twice and returns the existing order rather than creating a
 *    duplicate (e.g. on a flaky network retry).
 *
 * 2. **Optimistic locking** — `version` is incremented on every status change.
 *    Two admins editing the same order in two tabs cannot stomp each other:
 *    the UPDATE includes WHERE version = $oldVersion and any second writer gets
 *    0 rows affected → application shows "Order has been updated, refreshing."
 *
 * 3. **Order snapshot** — customer details are denormalized into the order row
 *    so subsequent edits to the user's profile do not change historical orders.
 *    Items also carry a snapshot — see order_items.
 *
 * 4. **Guest tracking** — `guest_track_token` is a cryptographically random
 *    UUID embedded in the order-confirmation email. Knowing the order_number
 *    is not enough; you need the token. Token is unique and unguessable.
 *
 * 5. **GDPR** — when the related user is hard-deleted, customer_id becomes NULL
 *    but the order survives (financial records have legal retention requirements).
 *    The denormalized fields are anonymized application-side via a separate job.
 */
export const orders = pgTable(
  "orders",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    /**
     * Public-facing order number (e.g. "2026-04-00123"). Generated by the API
     * via a sequence + format string; UNIQUE here to be safe.
     */
    orderNumber: text("order_number").notNull(),

    customerId: uuid("customer_id").references(() => users.id, {
      onDelete: "set null",
    }),

    version: integer("version").notNull().default(1),
    idempotencyKey: text("idempotency_key").notNull(),
    guestTrackToken: text("guest_track_token"),

    status: orderStatusEnum("status").notNull().default("processing"),
    paymentMethod: paymentMethodEnum("payment_method").notNull(),

    // Denormalized customer snapshot (always populated, even for logged-in users)
    customerEmail: text("customer_email").notNull(),
    customerPhone: text("customer_phone").notNull(),
    customerName: text("customer_name").notNull(),

    // Money columns store integer cents to avoid float drift. The rendered EUR
    // is computed as cents / 100 in the API; never multiplied through Number()
    // in JS in a way that loses precision.
    subtotalCents: numeric("subtotal_cents", { precision: 12, scale: 0 }).notNull(),
    discountPercent: numeric("discount_percent", { precision: 5, scale: 2 })
      .notNull()
      .default("0"),
    discountAmountCents: numeric("discount_amount_cents", { precision: 12, scale: 0 })
      .notNull()
      .default("0"),
    totalCents: numeric("total_cents", { precision: 12, scale: 0 }).notNull(),

    // Courier delivery — populated by admin when transitioning to "shipped"
    courierCompany: text("courier_company"),
    trackingNumber: text("tracking_number"),

    // Pickup — populated by admin when transitioning to "ready_for_pickup"
    pickupDeadline: timestamp("pickup_deadline", { withTimezone: true }),

    notes: text("notes"),
    cancelledReason: text("cancelled_reason"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`)
      .$onUpdate(() => new Date()),
    acceptedAt: timestamp("accepted_at", { withTimezone: true }),
  },
  (t) => [
    uniqueIndex("orders_order_number_unique").on(t.orderNumber),
    uniqueIndex("orders_idempotency_key_unique").on(t.idempotencyKey),
    uniqueIndex("orders_guest_track_token_unique").on(t.guestTrackToken),
    index("orders_customer_id_idx").on(t.customerId),
    index("orders_status_idx").on(t.status),
    index("orders_created_at_idx").on(t.createdAt),
    // Composite index for the admin "active orders" dashboard query
    index("orders_status_created_at_idx").on(t.status, t.createdAt),
    check("orders_amount_non_negative", sql`${t.totalCents} >= 0`),
    check(
      "orders_discount_percent_range",
      sql`${t.discountPercent} >= 0 AND ${t.discountPercent} <= 100`,
    ),
  ],
);

/**
 * Order line items — full snapshot of the product at the time of purchase.
 * Once written, these rows are immutable. The product_id reference is
 * informational only (SET NULL on product delete) — name/code/price are the
 * authoritative record.
 */
export const orderItems = pgTable(
  "order_items",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "cascade" }),
    productId: uuid("product_id").references(() => products.id, {
      onDelete: "set null",
    }),
    productCode: text("product_code").notNull(),
    productName: text("product_name").notNull(),
    productImageS3Key: text("product_image_s3_key"),
    unitPriceCents: numeric("unit_price_cents", { precision: 10, scale: 0 }).notNull(),
    quantity: integer("quantity").notNull(),
    discountAmountCents: numeric("discount_amount_cents", {
      precision: 12,
      scale: 0,
    })
      .notNull()
      .default("0"),
  },
  (t) => [
    index("order_items_order_id_idx").on(t.orderId),
    check("order_items_quantity_positive", sql`${t.quantity} > 0`),
    check("order_items_unit_price_non_negative", sql`${t.unitPriceCents} >= 0`),
  ],
);

/**
 * Corporate-order snapshot — only populated for orders placed by a corporate
 * account or by a corporate-typed guest. Pulled out of orders so the main
 * row stays focused.
 */
export const orderCorporateData = pgTable("order_corporate_data", {
  orderId: uuid("order_id")
    .primaryKey()
    .references(() => orders.id, { onDelete: "cascade" }),
  companyName: text("company_name").notNull(),
  eik: text("eik").notNull(),
  vatNumber: text("vat_number"),
  registeredAddress: text("registered_address").notNull(),
  mol: text("mol").notNull(),
  contactName: text("contact_name").notNull(),
});

/**
 * Delivery-address snapshot — only populated when payment_method =
 * 'cash_on_delivery'. Pickup orders skip this entirely.
 */
export const orderDeliveryAddress = pgTable("order_delivery_address", {
  orderId: uuid("order_id")
    .primaryKey()
    .references(() => orders.id, { onDelete: "cascade" }),
  city: text("city").notNull(),
  postalCode: text("postal_code").notNull(),
  street: text("street").notNull(),
  apartmentOrOffice: text("apartment_or_office"),
});

/**
 * Append-only status change log — enables the timeline view in the customer
 * profile and the audit trail for admins. Never updated, only inserted.
 */
export const orderStatusHistory = pgTable(
  "order_status_history",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "cascade" }),
    status: orderStatusEnum("status").notNull(),
    changedByUserId: uuid("changed_by_user_id").references(() => users.id, {
      onDelete: "set null",
    }),
    note: text("note"),
    changedAt: timestamp("changed_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [index("order_status_history_order_id_idx").on(t.orderId, t.changedAt)],
);

/**
 * 14-day complaint window per Bulgarian Consumer Protection Act / EU 2011/83/EU.
 * The platform only RECORDS complaints — actual handling happens via email/phone
 * outside the app (README §7).
 */
export const complaints = pgTable(
  "complaints",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    orderId: uuid("order_id")
      .notNull()
      .references(() => orders.id, { onDelete: "cascade" }),
    reason: complaintReasonEnum("reason").notNull(),
    description: text("description"),
    submittedAt: timestamp("submitted_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [index("complaints_order_id_idx").on(t.orderId)],
);
