import { Customer } from "@/lib/types";

export const customers: Customer[] = [
  {
    id: "cust-1",
    email: "ivan.petrov@example.com",
    firstName: "Иван",
    lastName: "Петров",
    phone: "+359 88 123 4567",
    accountType: "personal",
    discountPercent: 0,
    createdAt: "2025-08-15T10:00:00Z",
    isActive: true,
  },
  {
    id: "cust-2",
    email: "maria.georgieva@example.com",
    firstName: "Мария",
    lastName: "Георгиева",
    phone: "+359 87 234 5678",
    accountType: "corporate",
    companyName: "Технолоджи БГ ЕООД",
    vatNumber: "BG123456789",
    discountPercent: 10,
    createdAt: "2025-09-20T10:00:00Z",
    isActive: true,
  },
  {
    id: "cust-3",
    email: "stoyan.nikolov@example.com",
    firstName: "Стоян",
    lastName: "Николов",
    phone: "+359 89 345 6789",
    accountType: "corporate",
    companyName: "Строй Про ООД",
    vatNumber: "BG987654321",
    discountPercent: 15,
    createdAt: "2025-07-01T10:00:00Z",
    isActive: true,
  },
  {
    id: "cust-4",
    email: "elena.dimitrova@example.com",
    firstName: "Елена",
    lastName: "Димитрова",
    accountType: "personal",
    discountPercent: 5,
    createdAt: "2026-01-10T10:00:00Z",
    isActive: true,
  },
  {
    id: "cust-5",
    email: "georgi.ivanov@example.com",
    firstName: "Георги",
    lastName: "Иванов",
    phone: "+359 88 456 7890",
    accountType: "personal",
    discountPercent: 0,
    createdAt: "2026-02-22T10:00:00Z",
    isActive: false,
  },
];
