/**
 * Pure helpers for the admin dashboard (routes/admin/dashboard.ts).
 *
 * Kept dependency-free so the day-series zero-fill and the average-order-value
 * rounding can be unit-tested in isolation (tests/lib/dashboard-metrics.test.ts)
 * without a database — the same "pure helper beside the route" discipline the
 * order-status / product-admin / settings slices follow.
 */

/** One point on the daily trend line, oldest-first. Money is integer cents. */
export interface DaySeriesPoint {
  /** Europe/Sofia calendar date, `YYYY-MM-DD`. */
  date: string;
  orders: number;
  revenueCents: number;
}

/**
 * A day that actually had realised sales, as returned by the grouped SQL query.
 * The DB result is SPARSE — only days with at least one qualifying order appear.
 */
export interface DaySeriesRow {
  date: string;
  orders: number;
  revenueCents: number;
}

/**
 * Expand the sparse per-day SQL rows into a DENSE series of exactly `days`
 * points ending on `todayIso` (a Europe/Sofia `YYYY-MM-DD` calendar date),
 * oldest → newest, with missing days zero-filled.
 *
 * The axis is generated by decrementing calendar days from a **noon-UTC anchor**
 * (`${todayIso}T12:00:00Z`). Anchoring at noon rather than midnight means adding
 * or subtracting whole days via `setUTCDate` can never roll into the previous or
 * next calendar day through a sub-day offset — we are doing pure calendar
 * arithmetic on the date string, independent of any wall-clock timezone. A DB
 * row whose date is not on the generated axis (only possible in the sub-second
 * window where the JS "today" and the DB `now()` straddle Sofia midnight) is
 * simply ignored; the axis is authoritative.
 */
export function buildDaySeries(
  todayIso: string,
  days: number,
  rows: readonly DaySeriesRow[],
): DaySeriesPoint[] {
  const byDate = new Map<string, DaySeriesRow>();
  for (const r of rows) byDate.set(r.date, r);

  const anchor = new Date(`${todayIso}T12:00:00Z`);
  const out: DaySeriesPoint[] = [];
  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(anchor);
    d.setUTCDate(d.getUTCDate() - i);
    const date = d.toISOString().slice(0, 10);
    const hit = byDate.get(date);
    out.push({
      date,
      orders: hit ? hit.orders : 0,
      revenueCents: hit ? hit.revenueCents : 0,
    });
  }
  return out;
}

/**
 * Average order value in integer cents. Coherent with the sales figures it sits
 * beside: `revenueCents` and `orderCount` must be computed over the SAME set of
 * orders (realised sales — cancelled and returned excluded), so the quotient is
 * a real per-order average and not a ratio of two different populations.
 * Returns 0 when there are no qualifying orders (avoids a divide-by-zero and
 * reads correctly on an empty shop).
 */
export function averageOrderValueCents(
  revenueCents: number,
  orderCount: number,
): number {
  if (orderCount <= 0) return 0;
  return Math.round(revenueCents / orderCount);
}

/** The Europe/Sofia calendar date (`YYYY-MM-DD`) for an instant. */
export function sofiaDate(now: Date): string {
  // `en-CA` renders ISO-style `YYYY-MM-DD`; same idiom as jobs/catalog-backup.ts.
  return now.toLocaleDateString("en-CA", { timeZone: "Europe/Sofia" });
}
